name: Testnet check

on: 
  push:
    branches:
      - testnet-check
  pull_request:
    branches:
      - testnet-check

jobs:
  run-testnet-check:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout chain source code
        uses: actions/checkout@v3
      - name: setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Docker compose
        run: docker-compose up -d
      - name: check address balances
        run: bash homework/check-balances.sh
      - name: check chain id
        run: |
          CHAIN_ID=babyd status --node tcp://localhost:2281 | jq ".NodeInfo.network" -r
          if [ $CHAIN_ID == "toddler" ]
          then 
            echo "success: chain id is toddler"
          else
            echo "chain id is not toddler"
            exit 1
          fi