name: Testnet check

on: 
  - push

jobs:
  run-testnet-check:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout chain source code
        uses: actions/checkout@v3
      - name: run deploy-testnet homework script
        run: |
          screen -S testnode -d -m bash homework/deploy-testnet.sh
          screen -r testnode
      - name: terminate screen
        run: killall screen 2>/dev/null