name: Testnet check

on: 
  - push

jobs:
  run-testnet-check:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout chain source code
        uses: actions/checkout@v3
      - name: run deploy-testnet homework script
        run: |
          ls -a
          bash scripts/test-node-deploy.sh --install
      - name: query baby
        run: babyd status --node tcp://0.0.0.0:2281